export const dict = {
    pt: {
        loading: "Carregando...",
        youAreIn: "Você está em:",
        errors: "Erros:",
        wrongAttempts: "Tentativas Erradas:",
        dailyChallenge: "Desafio do dia:",
        origin: "Origem",
        destination: "Destino",
        para: "PARA",
        arrived: "Chegou!",
        alreadyArrived: "Você já chegou!",
        yourPath: "Seu Caminho",
        typeCountry: "Digite o nome do país...",
        startRoute: "Começar Rota",
        clickToRemove: "Clique para remover este país e os seguintes",
        errorValidating: "Erro ao validar tentativa.",
        invalidAttempt: "Tentativa inválida.",
        welcome: "Bem-vindo, Viajante!",
        welcomeMsg: "O objetivo do jogo é encontrar uma rota de fronteiras conectadas do país de <strong className='text-blue-600'>Origem</strong> até o país de <strong className='text-blue-600'>Destino</strong>.",
        noCountryNames: "Seu mapa global perdeu os nomes dos países!",
        originAndDest: "Origem e Destino:",
        correctPath: "País Verde Atual:",
        distantError: "Erros Vermelhos:",
        borderHint: "Países Amarelos:",
        passageHint: "", // não usado agora
        howItWorks: "Como funciona o mapa:",
        howOrigin: "Seus extremos (Início e Fim da viagem).",
        howCorrect: "O país verde é onde você está agora. O número acima dele indica a vez em que foi visitado.",
        grayCountries: "Os países cinzas são os já visitados, e caso volte a um país já visitado, ele é contado novamente na nova rota.",
        grayTip: "Países cinzas:",
        howDistant: "Essa cor significa que o país não faz fronteira com o país atual.",
        howBorder: "Os países amarelos são vizinhos do seu país atual que ainda não foram visitados.",
        howArrows: "", // não usado agora
        startTour: "Começar Passeio",
        completedTitle: "Viagem Concluída!",
        completedSub: "Você chegou ao seu destino!",
        perfectTitle: "Perfeito!",
        perfectSub: "Você escolheu a rota mais otimizada possível!",
        greatTitle: "Muito Bem!",
        greatSub: "Chegou super perto da rota ideal da perfeição!",
        totalSteps: "Total de Passos:",
        minSteps: "Passos Mínimos:",
        idealRoute: "ROTA IDEAL RECOMENDADA",
        seeMap: "Ver Mapa Final"
    },
    en: {
        loading: "Loading...",
        youAreIn: "You are in:",
        errors: "Errors:",
        wrongAttempts: "Wrong Attempts:",
        dailyChallenge: "Daily challenge:",
        origin: "Origin",
        destination: "Destination",
        para: "TO",
        arrived: "Arrived!",
        alreadyArrived: "You have arrived!",
        yourPath: "Your Path",
        typeCountry: "Type the country name...",
        startRoute: "Start Route",
        clickToRemove: "Click to remove this country and subsequent ones",
        errorValidating: "Error validating attempt.",
        invalidAttempt: "Invalid attempt.",
        welcome: "Welcome, Traveler!",
        welcomeMsg: "The goal of the game is to find a route of connected borders from the <strong className='text-blue-600'>Origin</strong> country to the <strong className='text-blue-600'>Destination</strong> country.",
        noCountryNames: "Your global map lost the country names!",
        originAndDest: "Origin and Destination:",
        correctPath: "Current Green Country:",
        distantError: "Red Errors:",
        borderHint: "Yellow Countries:",
        passageHint: "", // not used anymore
        howItWorks: "How the map works:",
        howOrigin: "Your endpoints (Start and End of the journey).",
        howCorrect: "The green country is where you currently are. The number above it shows which visit number it is.",
        howDistant: "Red means the guessed country did not border your current country.",
        howBorder: "Yellow countries are neighbors of your current country that have not been visited yet.",
        howArrows: "", // not used anymore
        grayCountries: "Gray countries are alreadyvisited; if you revisit a country it is counted again.",
        grayTip: "Gray Countries: ",
        startTour: "Start Tour",
        completedTitle: "Journey Complete!",
        completedSub: "You have reached your destination!",
        perfectTitle: "Perfect!",
        perfectSub: "You chose the most optimized route possible!",
        greatTitle: "Well Done!",
        greatSub: "You got really close to the perfect ideal route!",
        totalSteps: "Total Steps:",
        minSteps: "Minimum Steps:",
        idealRoute: "RECOMMENDED IDEAL ROUTE",
        seeMap: "See Final Map"
    }
};
