export const dict = {
  pt: {
    loading: "Carregando...",
    youAreIn: "Você está em:",
    errors: "Erros:",
    wrongAttempts: "Tentativas Erradas:",
    dailyChallenge: "Desafio do dia:",
    origin: "Origem",
    destination: "Destino",
    para: "PARA",
    arrived: "Chegou!",
    alreadyArrived: "Você já chegou!",
    yourPath: "Seu Caminho",
    typeCountry: "Digite o nome do país...",
    startRoute: "Começar Rota",
    clickToRemove: "Clique para remover este país e os seguintes",
    errorValidating: "Erro ao validar tentativa.",
    invalidAttempt: "Tentativa inválida.",
    welcome: "Bem-vindo, Viajante!",
    welcomeMsg: "O objetivo do jogo é encontrar uma rota de fronteiras conectadas do país de <strong className='text-blue-600'>Origem</strong> até o país de <strong className='text-blue-600'>Destino</strong>.",
    noCountryNames: "Seu mapa global perdeu os nomes dos países!",
    originAndDest: "Origem e Destino:",
    correctPath: "Caminho Correto (Números):",
    distantError: "Erro Distante:",
    borderHint: "Dica de Fronteira (Amarelo):",
    passageHint: "Dica de Passagem (Setinhas):",
    howItWorks: "Como funciona o mapa:",
    howOrigin: "Seus extremos (Início e Fim da viagem).",
    howCorrect: "Países que você acertou na rota. O número mostra a ordem em que você o visitou!",
    howDistant: "Você chutou esse país mas ele não faz fronteira com a sua posição atual.",
    howBorder: "Aquele país que você errou antes agora é VIZINHO da sua posição atual!",
    howArrows: "Linhas pontilhadas e setas amarelas no mapa marcam exatamente quais países fazem fronteira com a sua posição atual!",
    startTour: "Começar Passeio",
    completedTitle: "Viagem Concluída!",
    completedSub: "Você chegou ao seu destino!",
    perfectTitle: "Perfeito!",
    perfectSub: "Você escolheu a rota mais otimizada possível!",
    greatTitle: "Muito Bem!",
    greatSub: "Chegou super perto da rota ideal da perfeição!",
    totalSteps: "Total de Passos:",
    minSteps: "Passos Mínimos:",
    idealRoute: "ROTA IDEAL RECOMENDADA",
    seeMap: "Ver Mapa Final"
  },
  en: {
    loading: "Loading...",
    youAreIn: "You are in:",
    errors: "Errors:",
    wrongAttempts: "Wrong Attempts:",
    dailyChallenge: "Daily challenge:",
    origin: "Origin",
    destination: "Destination",
    para: "TO",
    arrived: "Arrived!",
    alreadyArrived: "You have arrived!",
    yourPath: "Your Path",
    typeCountry: "Type the country name...",
    startRoute: "Start Route",
    clickToRemove: "Click to remove this country and subsequent ones",
    errorValidating: "Error validating attempt.",
    invalidAttempt: "Invalid attempt.",
    welcome: "Welcome, Traveler!",
    welcomeMsg: "The goal of the game is to find a route of connected borders from the <strong className='text-blue-600'>Origin</strong> country to the <strong className='text-blue-600'>Destination</strong> country.",
    noCountryNames: "Your global map lost the country names!",
    originAndDest: "Origin and Destination:",
    correctPath: "Correct Path (Numbers):",
    distantError: "Distant Error:",
    borderHint: "Border Hint (Yellow):",
    passageHint: "Crossing Hint (Arrows):",
    howItWorks: "How the map works:",
    howOrigin: "Your endpoints (Start and End of the journey).",
    howCorrect: "Countries you correctly guessed on the route. The number shows the order you visited them!",
    howDistant: "You guessed this country but it does not border your current position.",
    howBorder: "That country you missed before is now a NEIGHBOR of your current position!",
    howArrows: "Dotted lines and yellow arrows on the map mark exactly which countries border your current position!",
    startTour: "Start Tour",
    completedTitle: "Journey Complete!",
    completedSub: "You have reached your destination!",
    perfectTitle: "Perfect!",
    perfectSub: "You chose the most optimized route possible!",
    greatTitle: "Well Done!",
    greatSub: "You got really close to the perfect ideal route!",
    totalSteps: "Total Steps:",
    minSteps: "Minimum Steps:",
    idealRoute: "RECOMMENDED IDEAL ROUTE",
    seeMap: "See Final Map"
  }
};
